### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by hummer007**

### CODE REVIEW

**Comment by solosky** [comment]
Hi sir, thank your contribution.

I have tested the PR, but failed, here are issues:

* The PR is broken, it even cannot compile, please correct the compile error first. 
* Regarding language contribution, please read https://github.com/solosky/pixl.js/blob/main/docs/en/05%2B5-translation.md before, please also commit updated i18n.csv. 
* I am not sure do the font wqy bdf have Russian glyph support or not , please do test the code before make PR. 
* Extra flash memory may used to store glyph of Russian charaters, we need reserve enough flash memory for further code enhancement.

**Review by solosky — CHANGES_REQUESTED** [review]
Please make changes according to my comments. 
Thanks.

**Comment by impeeza** [comment]
I was able to build a release using your commits as base and adding some files, but the result have a rare behavior:

image

image

The emulator and dabatabase have no title:
image
image

image

image


the space between characters is odd.

This are the files I did use, I don't know if @solosky can help on this.  may be the used font have the 

[ru.zip](https://github.com/solosky/pixl.js/files/14733571/ru.zip)

**Comment by impeeza** [comment]
the build is on 

https://github.com/impeeza/pixl.js/actions/runs/8404325329

**Comment by MayanKoyote** [comment]
Very good! But a few notes:

0. Russian ellipsis consists of three dots. Three. No more and no less.
1. https://github.com/solosky/pixl.js/blob/7ad3837df360ef0c6f336cae2044f0def869da9b/fw/application/src/i18n/ru_RU.c#L31
     -> "Возврат к настройкам по умолчанию" or "Восстановить настройки по умолчанию" or ""Сброс настроек к значениям по умолчанию""
     or simply "Сброс настроек" to fit the width of the our miniature screen.
2. https://github.com/solosky/pixl.js/blob/7ad3837df360ef0c6f336cae2044f0def869da9b/fw/application/src/i18n/ru_RU.c#L42
     but what if female will use the device?
     -> "Понятно"
3. https://github.com/solosky/pixl.js/blob/7ad3837df360ef0c6f336cae2044f0def869da9b/fw/application/src/i18n/ru_RU.c#L44
     От слова 'автослучка' что ли? Без комментариев. Тут Нужно придумать что то другое.
4. https://github.com/solosky/pixl.js/blob/7ad3837df360ef0c6f336cae2044f0def869da9b/fw/application/src/i18n/ru_RU.c#L81
     -> "[НАЗАД]"
5. https://github.com/solosky/pixl.js/blob/7ad3837df360ef0c6f336cae2044f0def869da9b/fw/application/src/i18n/ru_RU.c#L100
     -> "Обозреватель"
     на худой конец "Браузер" as option
6. https://github.com/solosky/pixl.js/blob/7ad3837df360ef0c6f336cae2044f0def869da9b/fw/application/src/i18n/ru_RU.c#L102
     -> or "Моё избранное..." or simply "Избранное..."
     coz of: https://github.com/solosky/pixl.js/blob/7ad3837df360ef0c6f336cae2044f0def869da9b/fw/application/src/i18n/ru_RU.c#L129
     -> or "Моя коллекция..."
     does not require unsaid semantic completion to gain meaning
7. https://github.com/solosky/pixl.js/blob/7ad3837df360ef0c6f336cae2044f0def869da9b/fw/application/src/i18n/ru_RU.c#L116
     -> "[Подробнее...]" maybe? Yes, our miniature screen.
8. Word 'Factory' in lines:
https://github.com/solosky/pixl.js/blob/7ad3837df360ef0c6f336cae2044f0def869da9b/fw/application/src/i18n/ru_RU.c#L152
https://github.com/solosky/pixl.js/blob/7ad3837df360ef0c6f336cae2044f0def869da9b/fw/application/src/i18n/ru_RU.c#L153
https://github.com/solosky/pixl.js/blob/7ad3837df360ef0c6f336cae2044f0def869da9b/fw/application/src/i18n/ru_RU.c#L168
I suspect that nothing related to the 'factory' as 'factory' was meant there.
A quick machine translation from Chinese (the original language here is Chinese) gives this:
     Reset..
     Card initialization successful
     Card type has been modified\nReset card data?

**Comment by MayanKoyote** [comment]
> * Extra flash memory may used to store glyph of Russian charaters, we need reserve enough flash memory for further code enhancement.

This will depend on how good the translation will look (fit into the width of the screen). Russian words are relatively long/wide.
But to understand this we need to see it on real screen first, and for this we need a suitable font.

**Comment by Wohlstand** [comment]
First in my mind why Russian glyphs drawn as this: they taken from the Chinese GBK charset, and to properly render Cyrillic it's need to have dedicated Cyrillic font that will have proper glyphs proportions

**Comment by solosky** [comment]
Close this PR because we have Russian support contributed by @MayanKoyote via #243

**Pull request closed without merging**
