### PR TITLE
Russian localization update related to commit 9a6c75e

### PR DESCRIPTION
**Pull request by MayanKoyote**
Changes related to commit 9a6c75e have been made.
___
Although I can't test it on the device screen since I can't flash the compiled firmware.
nFR Connect (Android) reports:
`[DFU] Remote DFU error: INSUFFICIENT RESOURCES`

Previous (old) self-assemblies are flashing perfectly.
Could it be because of the size? My pixljs.bin file size is currently 378140 bytes.
[Log 2024-11-20 12_33_11.txt](https://github.com/user-attachments/files/17826885/Log.2024-11-20.12_33_11.txt)

### CODE REVIEW

**Comment by solosky** [comment]
I haven't tried the DFU but flash the firmware successfully with jlink (tested on OLED version, LCD version haven't tested yet), let me try update with DFU later today.

**Comment by MayanKoyote** [comment]
Firmware from Actions run [11935777030](https://github.com/solosky/pixl.js/actions/runs/11935777030) with pixljs.bin of size 371308 bytes was successfully flashed via DFU.

**Comment by solosky** [comment]
Great!
Would you like the new feature?

**Comment by MayanKoyote** [comment]
I'm wondering what will happen when others update their translations? Will we run into size issues again?

As for the games, I didn't understand how to control some games. If everything is more or less clear with Tetris, then in the case of Lunar Lander everything becomes more complicated.

I also don't know what exactly the u8g2_font_wqy12_t_gb2312a.c file is responsible for and how to fix this conflict, so I'll just close this PR and create a new one.

**Pull request closed without merging**
