### PR TITLE
Move punctuation to i18n.csv

### LINKED ISSUE #236: The 'amibo' application automatically adds two-dot ellipsis to (some) text lines.
For most menu item text lines, the ellipsis is specified in the localization file.
For example, like here:
https://github.com/solosky/pixl.js/blob/223609b07aa2b97a6adfeb8b2932985d1c4d3e64/fw/application/src/i18n/pt_PT.c#L71
But in two cases (same app, 'amiibo'), the application itself adds a two-dot ellipsis instead:
https://github.com/solosky/pixl.js/blob/223609b07aa2b97a6adfeb8b2932985d1c4d3e64/fw/application/src/app/amiibo/scene/amiibo_scene_file_browser_menu.c#L301
https://github.com/solosky/pixl.js/blob/223609b07aa2b97a6adfeb8b2932985d1c4d3e64/fw/application/src/app/amiibo/scene/amiibo_scene_file_browser_menu.c#L303

Is it possible to put this in a uniform order (i.e. the ellipsis is specified in the localization file)?

### PR DESCRIPTION
**Pull request by Schokobecher**
This should close #236 

Changes:

- Moved hard-coded punctuation to i18n.csv
- Three dots instead of two (ellipsis typically have three)
- Added another string called `_L_DELETE_FILE` for use in `FILE_BROWSER_MENU_REMOVE_FOLDER`
- Updated the translations for `_L_DELETE_FILE` accordingly, please check if zh_Hans and zh_TW are useable
- Rebuilt language files

I compiled and flashed this version, and English/German look correct. Let me know if anything needs to be reworked, or I missed anything!

### CODE REVIEW

**Review by solosky — APPROVED** [review]
No comments.
Thanks for your contributions.

**Comment by MayanKoyote** [comment]
IMG_3491

What if to use:
for header text  - line [_L_APP_AMIIDB_TIPS], its content is: 'Confirm' in English, 'Hint' in Simplified Chinese, 'Attention' in Russian.
for confirmation button text - line [_L_CONFIRM], its content is: 'Confirm' in English, 'Sure' in Simplified Chinese, 'Yes' in Russian.
?

**Comment by impeeza** [comment]
Hello there, @solosky Should we then use on the CSV file the ellipsis character instead of the three dots?

for roman alphabet there is the Unicode Character «…» (U+2026); and as far I know, (for this please correct me) for Chinese, Unicode provides an explicitly centered U+22EF «⋯» MIDLINE HORIZONTAL ELLIPSIS character

that's OK or better to use the traditional dots?

**Comment by Schokobecher** [comment]
I agree with @MayanKoyote three "Delete" on one screen is a bit much, at least the button should be `_L_CONFIRM`

@impeeza I would prefer the Unicode version as its spacing is smaller compared to just regular dots. Both are included in `wenquanyi_9pt_u8g2.bdf` so it should be a drop-in replacement.

**Comment by impeeza** [comment]
Hello there, @Schokobecher which one is the unicode version?  I will like to try it on my branch before post a update

**Comment by Schokobecher** [comment]
@impeeza It's the one you posted, U+2026 and U+22EF are both provided by the font

**Comment by impeeza** [comment]
I was making some test and seems the FONT uses the same drawing for the ellipsis both are draw as tree dots on the middle of the vertical space look the custom created firmware:

image

image


image

my test file is on the branch ellipsis of my fork>

https://github.com/impeeza/pixl.js/blob/impeeza-Ellipsis/fw/data/i18n.csv

as you can see on the Chinese languages I use U+22EF and for the rest of languages U+2026 but on the device both are similar.  

U+22EF is like three dots 
image

U+2026 is like three small dashes. 
image

**Comment by impeeza** [comment]
By the way I am very pro to use the Unicode character for ellipsis instead of three separated dots

**Comment by MayanKoyote** [comment]
It's already have been discussed:
https://github.com/solosky/pixl.js/pull/208
So either look for other already-made ellipses in the font, or look for an empty space (if there is one) intended for one of the possible ellipsis options (so as not to spoil the font with gags) and draw the symbol yourself.

**Pull request merged**
